"""Stable public API for Limitora library consumers."""

from .api import (
    Clock,
    CurrentClock,
    Freshness,
    FreshnessPolicy,
    InvalidProviderSelectionError,
    InvalidStatusRequestError,
    StatusClient,
    StatusProvider,
    StatusRequest,
    StatusResult,
    StatusSnapshotResult,
    StatusUndetectedResult,
)
from .composition import (
    CodexJsonlConfig,
    CompositionError,
    CompositionErrorKind,
    OpenCodeGoConfig,
    ProviderConfig,
    activate_provider,
)
from .models import (
    MetricKind,
    ProviderId,
    ProviderSnapshot,
    ProviderState,
    ProviderStatus,
    RateLimitResetCredit,
    RateLimitResetCreditsSummary,
    RateLimitResetCreditStatus,
    RateLimitResetType,
    SourceMetadata,
)
from .providers import AuthorizationPolicy, ProviderError, ProviderErrorKind

__all__ = [
    "AuthorizationPolicy",
    "Clock",
    "CodexJsonlConfig",
    "CompositionError",
    "CompositionErrorKind",
    "CurrentClock",
    "Freshness",
    "FreshnessPolicy",
    "InvalidProviderSelectionError",
    "InvalidStatusRequestError",
    "MetricKind",
    "OpenCodeGoConfig",
    "ProviderError",
    "ProviderErrorKind",
    "ProviderId",
    "ProviderConfig",
    "ProviderSnapshot",
    "ProviderState",
    "ProviderStatus",
    "RateLimitResetCredit",
    "RateLimitResetCreditsSummary",
    "RateLimitResetCreditStatus",
    "RateLimitResetType",
    "SourceMetadata",
    "StatusClient",
    "StatusProvider",
    "StatusRequest",
    "StatusResult",
    "StatusSnapshotResult",
    "StatusUndetectedResult",
    "activate_provider",
]
